name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release -o output

      - name: Get system architecture (Windows)
        if: runner.os == 'Windows'
        run: |
          $arch = (Get-WmiObject Win32_OperatingSystem).OSArchitecture
          echo "Architecture=$arch" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Get system architecture (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          arch=$(uname -m)
          echo "Architecture=$arch" >> $GITHUB_ENV

      - name: Debugging - Print Architecture
        run: echo "Architecture=${{ env.Architecture }}"

      - name: Archive build files (Windows - PowerShell)
        if: runner.os == 'Windows'
        run: |
          $short_commit_id = $(git rev-parse --short HEAD)
          $artifact_name = "DQT-windows-${{ env.Architecture }}-$short_commit_id.zip"
          Write-Host "Artifact name: $artifact_name"
          Compress-Archive -Path output\* -DestinationPath $artifact_name
          Get-ChildItem -Path . -Filter "*.zip"

      - name: Archive build files (Linux/macOS - Bash)
        if: runner.os != 'Windows'
        run: |
          short_commit_id=$(git rev-parse --short HEAD)
          artifact_name="DQT-${{ runner.os }}-${{ env.Architecture }}-$short_commit_id.zip"
          echo "Artifact name: $artifact_name"
          zip -r $artifact_name output
          ls -l *.zip

      - name: Debugging - List ZIP files before uploading (Windows)
        if: runner.os == 'Windows'
        run: Get-ChildItem -Path . -Filter "*.zip"

      - name: Debugging - List ZIP files before uploading (Linux/macOS)
        if: runner.os != 'Windows'
        run: ls -l *.zip

      - name: Upload all zip artifacts with system info
        uses: actions/upload-artifact@v4
        with:
          name: DQT-artifacts-${{ runner.os }}-${{ env.Architecture }}-${{ github.run_id }}
          path: ./*.zip
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
